name: Add Theme
description: Submit a new theme to the marketplace
title: "[add-theme]: "
labels: ["theme-submission"]
body:
  - type: markdown
    attributes:
      value: |
        First time submitting a mod? The processs of adding mods to Sine is simple, all you have to do is add your github repository link and we'll handle the rest!
        Just make sure your repository has a valid theme.json with an id, name, description, and other properties.
        You can find out more about these properties in the [Wiki](https://github.com/CosmoCreeper/Sine/wiki)
  - type: input
    id: homepage
    attributes:
      label: Theme Homepage
      description: The GitHub repository URL containing your theme (must contain a theme.json file)
      placeholder: https://github.com/user/repo
    validations:
      required: true
