name: Add Theme
description: Submit a new theme to the marketplace
title: "[add-theme]: "
labels: ["theme-submission"]
body:
  - type: input
    id: homepage
    attributes:
      label: Theme Homepage
      description: The GitHub repository URL containing your theme (must contain a theme.json file)
      placeholder: https://github.com/user/repo
    validations:
      required: true
